---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-api
  template:
    metadata:
      labels:
        app: flask-api
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: flask-api-container
          image: mon-app-flask:latest
          ports:
            - containerPort: 8080
