---
name: Pipeline DevSecOps

"on":
  push:
    branches: ["main"]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Linter les fichiers YAML
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: .

      - name: Linter le Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

      #  PARTIE 3 ---
      # Scan des dépendances logicielles (requirements.txt)
      - name: Scan des dependances (Trivy FS)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          scan-ref: "."
          format: "table"
          severity: "CRITICAL,HIGH"

      - name: Build de l'image Docker
        run: docker build -t mon-api-flask:latest .

      # Scan de l'image Docker construite
      - name: Scan de l'image Docker (Trivy Image)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "mon-api-flask:latest"
          format: "table"
          severity: "CRITICAL,HIGH"

      #      PARTIE 4
      # Verification des politiques avec Conftest
      - name: Installer Conftest
        run: |
          URL="https://github.com/open-policy-agent/conftest"
          VER="v0.46.0"
          FILE="conftest_0.46.0_Linux_x86_64.tar.gz"
          wget "$URL/releases/download/$VER/$FILE"
          tar xzf "$FILE"
          sudo mv conftest /usr/local/bin

      - name: Run Conftest sur k8s.yaml
        run: conftest test k8s.yaml -p policy/deployment.rego
